# Generated by Django 5.0.3 on 2024-03-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='tmdbId',
            field=models.IntegerField(default=0),
        ),
    ]
