# Generated by Django 5.0.3 on 2024-03-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_alter_link_imdbid_alter_link_tmdbid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='rating',
            name='timestampNew',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='timestampNew',
            field=models.BigIntegerField(default=0),
        ),
    ]
